import { Router } from "express";
import { storage } from "../storage";
import { insertAgentRecommendationSchema } from "@shared/schema";
import * as fs from "fs";
import * as path from "path";

const router = Router();

const VALID_CATEGORIES = new Set(["code_snippet", "file_edit", "systemic", "integration", "new_tool"]);
const VALID_PRIORITIES = new Set(["low", "medium", "high", "critical"]);
const VALID_STATUSES = new Set(["proposed", "accepted", "implemented", "rejected"]);

const recentSubmissions = new Map<string, number>();
const SERVER_RATE_LIMIT_MS = 2000;
const MAX_STORED_ITEMS = 300;

function isDuplicate(title: string): boolean {
  const key = title.trim().toLowerCase().slice(0, 60);
  const now = Date.now();
  const last = recentSubmissions.get(key);
  if (last && now - last < 60000) return true;
  recentSubmissions.set(key, now);
  if (recentSubmissions.size > 200) {
    const entries = Array.from(recentSubmissions.entries())
      .sort((a, b) => a[1] - b[1])
      .slice(0, 100);
    entries.forEach(([k]) => recentSubmissions.delete(k));
  }
  return false;
}

let lastSubmitTime = 0;

const CATEGORY_LABELS: Record<string, string> = {
  code_snippet: "Code Snippet",
  file_edit: "File Edit",
  systemic: "Systemic Improvement",
  integration: "Integration",
  new_tool: "New Tool",
};

const PRIORITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "⚪",
};

function recToPrompt(rec: any): string {
  const lines = [
    `## Task: ${rec.title}`,
    `**Category**: ${CATEGORY_LABELS[rec.category] || rec.category}`,
    `**Priority**: ${rec.priority}`,
    ``,
    `### Description`,
    rec.description,
    ``,
  ];
  if (rec.targetFiles && rec.targetFiles.length > 0) {
    lines.push(`### Target Files`);
    rec.targetFiles.forEach((f: string) => lines.push(`- \`${f}\``));
    lines.push(``);
  }
  if (rec.painPointsAddressed && rec.painPointsAddressed.length > 0) {
    lines.push(`### Pain Points This Solves`);
    rec.painPointsAddressed.forEach((p: string) => lines.push(`- ${p}`));
    lines.push(``);
  }
  if (rec.codeSnippet) {
    lines.push(`### Starter Code`);
    lines.push(`\`\`\`${rec.codeLanguage || 'typescript'}`);
    lines.push(rec.codeSnippet);
    lines.push(`\`\`\``);
    lines.push(``);
  }
  if (rec.estimatedImpact) {
    lines.push(`### Expected Impact`);
    lines.push(rec.estimatedImpact);
    lines.push(``);
  }
  return lines.join('\n');
}

function recToAgentPrompt(rec: any): string {
  const parts = [
    `Implement the following change in this codebase:`,
    ``,
    `TITLE: ${rec.title}`,
    `CATEGORY: ${CATEGORY_LABELS[rec.category] || rec.category}`,
    `PRIORITY: ${rec.priority}`,
    ``,
    `WHAT TO DO:`,
    rec.description,
  ];
  if (rec.targetFiles && rec.targetFiles.length > 0) {
    parts.push(``, `FILES TO MODIFY:`);
    rec.targetFiles.forEach((f: string) => parts.push(`  - ${f}`));
  }
  if (rec.painPointsAddressed && rec.painPointsAddressed.length > 0) {
    parts.push(``, `PAIN POINTS THIS FIXES:`);
    rec.painPointsAddressed.forEach((p: string) => parts.push(`  - ${p}`));
  }
  if (rec.codeSnippet) {
    parts.push(``, `STARTER CODE (use as reference, adapt to codebase patterns):`);
    parts.push(`\`\`\`${rec.codeLanguage || 'typescript'}`);
    parts.push(rec.codeSnippet);
    parts.push(`\`\`\``);
  }
  if (rec.estimatedImpact) {
    parts.push(``, `EXPECTED IMPACT: ${rec.estimatedImpact}`);
  }
  parts.push(``, `INSTRUCTIONS: Read the target files first, understand existing patterns, then implement this change following project conventions (React + TypeScript + Tailwind + Drizzle ORM). Test your changes.`);
  return parts.join('\n');
}

function generateMarkdown(recs: any[]): string {
  const now = new Date().toISOString().split('T')[0];
  const lines = [
    `# Agent Recommendations`,
    ``,
    `> Auto-generated by NEXUS agents. Last synced: ${now}`,
    `> These are actionable platform improvements with starter code.`,
    `> Feed individual items to any coding agent (Replit, Cursor, Copilot, Claude, etc.) to implement them.`,
    ``,
    `| # | Category | Priority | Title | Pain Points | Status |`,
    `|---|----------|----------|-------|-------------|--------|`,
  ];

  recs.forEach((rec, i) => {
    const pp = (rec.painPointsAddressed || []).length;
    lines.push(`| ${i + 1} | ${CATEGORY_LABELS[rec.category] || rec.category} | ${PRIORITY_EMOJI[rec.priority] || ''} ${rec.priority} | ${rec.title} | ${pp} | ${rec.status} |`);
  });

  lines.push(``, `---`, ``);

  const grouped: Record<string, any[]> = {};
  recs.forEach(rec => {
    const cat = rec.category;
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(rec);
  });

  for (const [cat, items] of Object.entries(grouped)) {
    lines.push(`## ${CATEGORY_LABELS[cat] || cat}s`, ``);
    items.forEach(rec => {
      lines.push(recToPrompt(rec));
      lines.push(`---`, ``);
    });
  }

  lines.push(``, `## How to Use These Recommendations`, ``);
  lines.push(`### With any AI coding agent`);
  lines.push(`Copy a single recommendation section above and paste it as a prompt to your coding agent.`);
  lines.push(``);
  lines.push(`### Via API`);
  lines.push(`\`\`\`bash`);
  lines.push(`# Fetch all recommendations as JSON`);
  lines.push(`curl -s https://YOUR_APP_URL/api/recommendations/export?format=json`);
  lines.push(``);
  lines.push(`# Fetch a single recommendation as an agent-ready prompt`);
  lines.push(`curl -s https://YOUR_APP_URL/api/recommendations/export/1?format=prompt`);
  lines.push(`\`\`\``);
  lines.push(``);
  lines.push(`### Programmatic ingestion`);
  lines.push(`\`\`\`bash`);
  lines.push(`# Pipe a recommendation directly into another tool`);
  lines.push(`curl -s https://YOUR_APP_URL/api/recommendations/export/1?format=prompt | pbcopy`);
  lines.push(`\`\`\``);

  return lines.join('\n');
}

async function syncToFiles(recs: any[]) {
  try {
    const githubDir = path.join(process.cwd(), '.github');
    if (!fs.existsSync(githubDir)) fs.mkdirSync(githubDir, { recursive: true });

    const md = generateMarkdown(recs);
    fs.writeFileSync(path.join(githubDir, 'RECOMMENDATIONS.md'), md, 'utf-8');

    const jsonExport = recs.map(rec => ({
      id: rec.id,
      category: rec.category,
      priority: rec.priority,
      status: rec.status,
      title: rec.title,
      description: rec.description,
      targetFiles: rec.targetFiles || [],
      codeSnippet: rec.codeSnippet || null,
      codeLanguage: rec.codeLanguage || 'typescript',
      painPointsAddressed: rec.painPointsAddressed || [],
      estimatedImpact: rec.estimatedImpact || null,
      source: rec.source,
      votes: rec.votes,
      createdAt: rec.createdAt,
    }));
    fs.writeFileSync(path.join(githubDir, 'recommendations.json'), JSON.stringify(jsonExport, null, 2), 'utf-8');
  } catch (err) {
    console.error('Failed to sync recommendations to files:', err);
  }
}

router.get("/", async (_req, res) => {
  try {
    const items = await storage.getAllRecommendations();
    res.json(items);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.get("/stats", async (_req, res) => {
  try {
    const items = await storage.getAllRecommendations();
    const stats = {
      total: items.length,
      byCategory: {} as Record<string, number>,
      byStatus: { proposed: 0, accepted: 0, implemented: 0, rejected: 0 } as Record<string, number>,
      byPriority: { critical: 0, high: 0, medium: 0, low: 0 } as Record<string, number>,
      topVoted: items.sort((a, b) => b.votes - a.votes).slice(0, 5),
      painPointsCovered: [] as string[],
    };
    const painSet = new Set<string>();
    items.forEach(item => {
      stats.byCategory[item.category] = (stats.byCategory[item.category] || 0) + 1;
      stats.byStatus[item.status] = (stats.byStatus[item.status] || 0) + 1;
      stats.byPriority[item.priority] = (stats.byPriority[item.priority] || 0) + 1;
      if (item.painPointsAddressed) {
        item.painPointsAddressed.forEach((p: string) => painSet.add(p));
      }
    });
    stats.painPointsCovered = Array.from(painSet);
    res.json(stats);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.get("/export", async (req, res) => {
  try {
    const items = await storage.getAllRecommendations();
    const format = (req.query.format as string) || 'json';
    const category = req.query.category as string;
    const status = req.query.status as string;

    let filtered = items;
    if (category && VALID_CATEGORIES.has(category)) {
      filtered = filtered.filter(i => i.category === category);
    }
    if (status && VALID_STATUSES.has(status)) {
      filtered = filtered.filter(i => i.status === status);
    }

    if (format === 'markdown' || format === 'md') {
      res.setHeader('Content-Type', 'text/markdown');
      res.send(generateMarkdown(filtered));
    } else if (format === 'prompt') {
      res.setHeader('Content-Type', 'text/plain');
      const prompts = filtered.map(r => recToAgentPrompt(r));
      res.send(prompts.join('\n\n' + '='.repeat(80) + '\n\n'));
    } else {
      res.json({
        exported: new Date().toISOString(),
        count: filtered.length,
        recommendations: filtered.map(rec => ({
          id: rec.id,
          category: rec.category,
          priority: rec.priority,
          status: rec.status,
          title: rec.title,
          description: rec.description,
          targetFiles: rec.targetFiles || [],
          codeSnippet: rec.codeSnippet || null,
          codeLanguage: rec.codeLanguage || 'typescript',
          painPointsAddressed: rec.painPointsAddressed || [],
          estimatedImpact: rec.estimatedImpact || null,
          source: rec.source,
          votes: rec.votes,
        })),
      });
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.get("/export/:id", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    if (isNaN(id)) return res.status(400).json({ error: "Invalid ID" });
    const rec = await storage.getRecommendationById(id);
    if (!rec) return res.status(404).json({ error: "Not found" });

    const format = (req.query.format as string) || 'json';

    if (format === 'prompt') {
      res.setHeader('Content-Type', 'text/plain');
      res.send(recToAgentPrompt(rec));
    } else if (format === 'markdown' || format === 'md') {
      res.setHeader('Content-Type', 'text/markdown');
      res.send(recToPrompt(rec));
    } else {
      res.json(rec);
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.post("/sync", async (_req, res) => {
  try {
    const items = await storage.getAllRecommendations();
    await syncToFiles(items);
    res.json({ synced: items.length, files: ['.github/RECOMMENDATIONS.md', '.github/recommendations.json'] });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.post("/", async (req, res) => {
  try {
    const now = Date.now();
    if (now - lastSubmitTime < SERVER_RATE_LIMIT_MS) {
      return res.status(429).json({ error: "Too many submissions, slow down" });
    }
    lastSubmitTime = now;

    const body = req.body;
    if (!body.title || typeof body.title !== "string" || body.title.trim().length < 3) {
      return res.status(400).json({ error: "Title must be at least 3 characters" });
    }
    if (!body.description || typeof body.description !== "string" || body.description.trim().length < 5) {
      return res.status(400).json({ error: "Description must be at least 5 characters" });
    }
    if (body.category && !VALID_CATEGORIES.has(body.category)) {
      return res.status(400).json({ error: "Invalid category" });
    }
    if (body.priority && !VALID_PRIORITIES.has(body.priority)) {
      return res.status(400).json({ error: "Invalid priority" });
    }

    body.title = body.title.trim().slice(0, 200);
    body.description = body.description.trim().slice(0, 3000);
    if (body.codeSnippet) body.codeSnippet = String(body.codeSnippet).slice(0, 10000);
    if (body.codeLanguage) body.codeLanguage = String(body.codeLanguage).slice(0, 30);
    if (body.estimatedImpact) body.estimatedImpact = String(body.estimatedImpact).slice(0, 500);
    if (body.source) body.source = String(body.source).slice(0, 100);
    if (body.targetFiles && Array.isArray(body.targetFiles)) {
      body.targetFiles = body.targetFiles.slice(0, 10).map((f: any) => String(f).slice(0, 200));
    }
    if (body.painPointsAddressed && Array.isArray(body.painPointsAddressed)) {
      body.painPointsAddressed = body.painPointsAddressed.slice(0, 10).map((p: any) => String(p).slice(0, 200));
    }
    if (body.tags && Array.isArray(body.tags)) {
      body.tags = body.tags.slice(0, 10).map((t: any) => String(t).slice(0, 50));
    }

    if (isDuplicate(body.title)) {
      return res.status(409).json({ error: "Duplicate recommendation recently submitted" });
    }

    const existing = await storage.getAllRecommendations();
    if (existing.length >= MAX_STORED_ITEMS) {
      return res.status(507).json({ error: "Recommendation storage limit reached" });
    }

    const parsed = insertAgentRecommendationSchema.parse(body);
    const item = await storage.createRecommendation(parsed);

    syncToFiles([...existing, item]).catch(() => {});

    res.json(item);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

router.patch("/:id", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    if (isNaN(id)) return res.status(400).json({ error: "Invalid ID" });

    const updates: Record<string, any> = {};
    if (req.body.status && VALID_STATUSES.has(req.body.status)) updates.status = req.body.status;
    if (req.body.priority && VALID_PRIORITIES.has(req.body.priority)) updates.priority = req.body.priority;

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({ error: "No valid updates provided" });
    }

    const updated = await storage.updateRecommendation(id, updates);
    if (!updated) return res.status(404).json({ error: "Not found" });
    res.json(updated);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.post("/:id/vote", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    if (isNaN(id)) return res.status(400).json({ error: "Invalid ID" });
    const updated = await storage.voteRecommendation(id);
    if (!updated) return res.status(404).json({ error: "Not found" });
    res.json(updated);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    if (isNaN(id)) return res.status(400).json({ error: "Invalid ID" });
    const deleted = await storage.deleteRecommendation(id);
    if (!deleted) return res.status(404).json({ error: "Not found" });
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
