import { ArcTemplate, CampaignNode, CampaignLink, HiddenClue, ClueType, mkNode, mkLink, mkClue } from './CampaignTypes';

export const CIVIC_ARC_TEMPLATES: ArcTemplate[] = [
  { name: 'Movement Case Study', desc: 'Historical movement analysis', category: 'civic', nodes: [
    mkNode('mcs1','step','Choose Movement','Select a movement to study (Serbia, Ukraine, Hong Kong, etc.). Proceed to [[Context Research]].',0,0),
    mkNode('mcs2','tool','Context Research','Gather historical context, key actors, timeline. See [[Tactic Analysis]].',300,0),
    mkNode('mcs3','step','Tactic Analysis','Analyze humor, unity-building, and key turning points. Proceed to [[Lesson Extraction]].',600,0),
    mkNode('mcs4','output','Lesson Extraction','Document lessons for contemporary organizers.',900,0),
  ], links: [mkLink('mcs1','mcs2'),mkLink('mcs2','mcs3'),mkLink('mcs3','mcs4')],
    clues: [mkClue('source-code','mcs3','Check page source for key slogan','Gotov je'),mkClue('meta-tag','mcs4','Meta description contains movement outcome','democratic transition')]},
  { name: 'Grassroots Campaign', desc: 'Organizing from the ground up', category: 'civic', nodes: [
    mkNode('gc1','step','Issue Selection','Identify a winnable, meaningful issue. Map [[Power Analysis]].',0,0),
    mkNode('gc2','tool','Power Analysis','Identify decision-makers, allies, opposition. See [[One-on-One Plan]].',300,0),
    mkNode('gc3','step','One-on-One Plan','Design relational conversations. Build [[Leadership Team]].',600,0),
    mkNode('gc4','output','Leadership Team','Document key leaders and campaign structure.',900,0),
  ], links: [mkLink('gc1','gc2'),mkLink('gc2','gc3'),mkLink('gc3','gc4')],
    clues: [mkClue('data-attribute','gc2','data-power-level for key actor','5'),mkClue('console-log','gc4','Console shows coalition size','leaders: 12')]},
  { name: 'Digital Citizenship', desc: 'Information integrity and safe engagement', category: 'civic', nodes: [
    mkNode('dc1','step','Claim Identification','Identify a viral claim or image to verify. Proceed to [[Fact-Check]].',0,0),
    mkNode('dc2','tool','Fact-Check','Reverse image search, source verification, cross-reference. See [[Context Assessment]].',300,0),
    mkNode('dc3','step','Context Assessment','Evaluate reliability, potential harm of sharing. Proceed to [[Ethical Decision]].',600,0),
    mkNode('dc4','output','Ethical Decision','Document verification result and sharing recommendation.',900,0),
  ], links: [mkLink('dc1','dc2'),mkLink('dc2','dc3'),mkLink('dc3','dc4')],
    clues: [mkClue('http-header','dc2','X-Origin-Date header','2020-03-15'),mkClue('base64','dc4','Base64 verification summary','VmVyaWZpZWQ6IEZhbHNl')]},
  { name: 'Humor and Unity', desc: 'Tactical humor and unity-building', category: 'civic', nodes: [
    mkNode('hu1','step','Legitimacy Analysis','Identify regime or authority source of legitimacy. See [[Ridicule Design]].',0,0),
    mkNode('hu2','tool','Ridicule Design','Design satirical campaign that exposes absurdity. Proceed to [[Unity Message]].',300,0),
    mkNode('hu3','step','Unity Message','Craft message that transcends divides. See [[Tactical Plan]].',600,0),
    mkNode('hu4','output','Tactical Plan','Document humor + unity campaign plan.',900,0),
  ], links: [mkLink('hu1','hu2'),mkLink('hu2','hu3'),mkLink('hu3','hu4')],
    clues: [mkClue('source-code','hu2','Comment contains satire example','<!-- Gotov je! -->'),mkClue('data-attribute','hu4','data-coalition-breadth','broad')]},
  { name: 'Civic Engagement Starter', desc: 'Beginner civic participation', category: 'civic', nodes: [
    mkNode('ces1','step','Government Map','Map local government structure and decision points. See [[Participation Opportunities]].',0,0),
    mkNode('ces2','tool','Participation Opportunities','Find meetings, votes, contact points. Proceed to [[First Action]].',300,0),
    mkNode('ces3','output','First Action','Choose and schedule your first civic action.',600,0),
  ], links: [mkLink('ces1','ces2'),mkLink('ces2','ces3')],
    clues: [mkClue('meta-tag','ces1','Meta keywords include jurisdiction','city council')]},
];

export const ARC_TEMPLATES: ArcTemplate[] = [
  { name: 'Phantom Thread', desc: 'Phishing / Initial Access', category: 'social', nodes: [
    mkNode('pt1','step','Suspicious Email','Analyze the phishing email. Check [[Sender Analysis]] for header clues.',0,0),
    mkNode('pt2','tool','Sender Analysis','Run DKIM/SPF checks. Forward to [[Payload Extraction]].',300,0),
    mkNode('pt3','step','Payload Extraction','Extract the malicious attachment. See [[Credential Harvest]].',600,0),
    mkNode('pt4','output','Credential Harvest','Document captured credentials and IOCs.',900,0),
  ], links: [mkLink('pt1','pt2'),mkLink('pt2','pt3'),mkLink('pt3','pt4')],
    clues: [mkClue('source-code','pt3','Check the HTML source for a hidden form action','https://evil.corp/harvest'),mkClue('http-header','pt1','Inspect X-Originating-IP header','192.168.13.37')]},
  { name: 'Ghost Protocol', desc: 'Persistence / Backdoor', category: 'exploit', nodes: [
    mkNode('gp1','step','Initial Foothold','Enumerate services. Proceed to [[Registry Persistence]].',0,0),
    mkNode('gp2','tool','Registry Persistence','Plant RunOnce key. Verify with [[Callback Verification]].',300,0),
    mkNode('gp3','output','Callback Verification','Confirm C2 beacon established.',600,0),
  ], links: [mkLink('gp1','gp2'),mkLink('gp2','gp3')],
    clues: [mkClue('console-log','gp2','Check browser console for encoded beacon','beacon_active=true'),mkClue('data-attribute','gp3','Look for data-status attribute','persistence-confirmed')]},
  { name: 'Shadow Network', desc: 'OSINT Recon', category: 'osint', nodes: [
    mkNode('sn1','step','Target Profile','Gather initial intel on target. Check [[Domain Recon]].',0,0),
    mkNode('sn2','tool','Domain Recon','WHOIS/DNS enumeration. See [[Social Footprint]].',300,0),
    mkNode('sn3','step','Social Footprint','Map social accounts. Cross-ref with [[Dark Web Search]].',600,0),
    mkNode('sn4','tool','Dark Web Search','Search .onion indexes for mentions. See [[Intel Report]].',300,200),
    mkNode('sn5','output','Intel Report','Compile findings into structured report.',600,200),
  ], links: [mkLink('sn1','sn2'),mkLink('sn2','sn3'),mkLink('sn3','sn4'),mkLink('sn4','sn5')],
    clues: [mkClue('meta-tag','sn1','Check meta author tag','agent_shadow'),mkClue('css-comment','sn3','Hidden CSS comment reveals alias','/* alias: gh0st_runner */'),mkClue('base64','sn5','Decode the base64 string in the report footer','U2hhZG93IE5ldHdvcms=')]},
  { name: 'Wire Transfer', desc: 'Financial / Crypto Tracing', category: 'forensics', nodes: [
    mkNode('wt1','step','Transaction Alert','Suspicious transfer flagged. Trace via [[Blockchain Explorer]].',0,0),
    mkNode('wt2','tool','Blockchain Explorer','Follow the money through mixers. See [[Exchange KYC]].',300,0),
    mkNode('wt3','step','Exchange KYC','Subpoena exchange records. Compile in [[Financial Report]].',600,0),
    mkNode('wt4','output','Financial Report','Document the complete money trail.',900,0),
  ], links: [mkLink('wt1','wt2'),mkLink('wt2','wt3'),mkLink('wt3','wt4')],
    clues: [mkClue('network-request','wt2','Inspect XHR for hidden wallet address','bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh'),mkClue('hex-encoded','wt4','Decode hex in transaction memo','4d6f6e6579204c61756e646572696e67')]},
  { name: 'Social Spider', desc: 'Social Engineering', category: 'social', nodes: [
    mkNode('ss1','step','Target Selection','Identify high-value target. Build [[Pretext Profile]].',0,0),
    mkNode('ss2','step','Pretext Profile','Craft believable cover story. Plan [[Vishing Call]].',300,0),
    mkNode('ss3','tool','Vishing Call','Execute voice phishing. Record in [[Debrief]].',600,0),
    mkNode('ss4','output','Debrief','Document what intel was extracted.',900,0),
  ], links: [mkLink('ss1','ss2'),mkLink('ss2','ss3'),mkLink('ss3','ss4')],
    clues: [mkClue('http-header','ss1','Check custom X-Agent header','spider-agent-7'),mkClue('source-code','ss3','View source for hidden script tag','<script>reportBack("success")</script>')]},
  { name: 'Dark Mirror', desc: 'Dark Web Intel', category: 'osint', nodes: [
    mkNode('dm1','step','Surface Scan','Search clearnet for breadcrumbs. Follow to [[Onion Crawl]].',0,0),
    mkNode('dm2','tool','Onion Crawl','Crawl hidden services. Document in [[Intel Dossier]].',300,0),
    mkNode('dm3','output','Intel Dossier','Compile dark web intelligence report.',600,0),
  ], links: [mkLink('dm1','dm2'),mkLink('dm2','dm3')],
    clues: [mkClue('steganography','dm2','Image contains hidden data','dead_drop_location_42'),mkClue('base64','dm3','Base64 in page footer','RGFyayBNaXJyb3IgQWN0aXZl')]},
  { name: 'Packet Storm', desc: 'Network Forensics', category: 'forensics', nodes: [
    mkNode('ps1','step','Capture Traffic','Start packet capture on suspect interface. Analyze in [[Protocol Analysis]].',0,0),
    mkNode('ps2','tool','Protocol Analysis','Deep-dive into anomalous packets. Check [[DNS Tunneling]].',300,0),
    mkNode('ps3','decision','DNS Tunneling','Is data being exfiltrated via DNS? See [[Forensic Report]].',600,0),
    mkNode('ps4','output','Forensic Report','Document network forensics findings.',900,0),
  ], links: [mkLink('ps1','ps2'),mkLink('ps2','ps3'),mkLink('ps3','ps4')],
    clues: [mkClue('console-log','ps1','Console shows hidden packet count','captured_packets: 1337'),mkClue('network-request','ps2','XHR reveals C2 domain','c2.malware.internal'),mkClue('http-header','ps4','Response header contains case ID','X-Case-ID: PKT-2026-001')]},
  { name: 'Zero Day', desc: 'Vulnerability Research', category: 'exploit', nodes: [
    mkNode('zd1','step','Attack Surface','Map the application attack surface. Start [[Fuzzing]].',0,0),
    mkNode('zd2','tool','Fuzzing','Fuzz input parameters. Crashes lead to [[Root Cause]].',300,0),
    mkNode('zd3','step','Root Cause','Analyze crash dump. Develop [[Exploit PoC]].',600,0),
    mkNode('zd4','tool','Exploit PoC','Build proof-of-concept exploit. Write [[Advisory]].',300,200),
    mkNode('zd5','output','Advisory','Responsible disclosure report.',600,200),
  ], links: [mkLink('zd1','zd2'),mkLink('zd2','zd3'),mkLink('zd3','zd4'),mkLink('zd4','zd5')],
    clues: [mkClue('source-code','zd2','View source for buffer size hint','MAX_BUF=256'),mkClue('data-attribute','zd3','data-vuln-class attribute','heap-overflow'),mkClue('css-comment','zd5','CSS comment has CVE','/* CVE-2026-31337 */')]},
  { name: 'Red Herring', desc: 'Counter-Intelligence', category: 'defense', nodes: [
    mkNode('rh1','step','Threat Detection','Anomaly detected. Is it real or a [[Decoy Analysis]]?',0,0),
    mkNode('rh2','decision','Decoy Analysis','Determine if this is misdirection. Report in [[CI Brief]].',300,0),
    mkNode('rh3','output','CI Brief','Counter-intelligence assessment.',600,0),
  ], links: [mkLink('rh1','rh2'),mkLink('rh2','rh3')],
    clues: [mkClue('meta-tag','rh1','Meta tag reveals true origin','origin: counterintel-unit-9'),mkClue('hex-encoded','rh3','Hex string in report','5265642048657272696e67')]},
  { name: 'First Contact', desc: 'Beginner Tutorial', category: 'recon', nodes: [
    mkNode('fc1','step','Welcome','Welcome to your first investigation! Start by reading [[Gather Clues]].',0,0),
    mkNode('fc2','step','Gather Clues','Look around the page for hidden information. Then [[Write Report]].',300,0),
    mkNode('fc3','output','Write Report','Summarize what you found. Congratulations!',600,0),
  ], links: [mkLink('fc1','fc2'),mkLink('fc2','fc3')],
    clues: [mkClue('source-code','fc2','Right-click and View Source to find the flag','FLAG{welcome_agent}')]},
  { name: 'APT Attribution', desc: 'Nation-State Attribution Analysis', category: 'osint', nodes: [
    mkNode('aa1','step','Initial Indicators','Collect initial IOCs from the incident — hashes, IPs, domains. Cross-reference with threat intel feeds. Proceed to [[Infrastructure Analysis]].',0,0),
    mkNode('aa2','tool','Infrastructure Analysis','Map attacker infrastructure using passive DNS and WHOIS pivoting. Identify hosting providers and registration patterns. Proceed to [[Malware Family ID]].',300,0),
    mkNode('aa3','step','Malware Family ID','Analyze malware samples to identify family, packer, and compiler artifacts. Extract configuration data and C2 addresses. Proceed to [[TTP Mapping (MITRE ATT&CK)]].',600,0),
    mkNode('aa4','tool','TTP Mapping (MITRE ATT&CK)','Map observed tactics, techniques, and procedures to the MITRE ATT&CK framework. Identify technique overlaps with known threat groups. Proceed to [[Attribution Assessment]].',300,200),
    mkNode('aa5','output','Attribution Assessment','Synthesize infrastructure, malware, and TTP evidence to assess attribution confidence level. Document findings with diamond model analysis.',600,200),
  ], links: [mkLink('aa1','aa2'),mkLink('aa2','aa3'),mkLink('aa3','aa4'),mkLink('aa4','aa5')],
    clues: [mkClue('meta-tag','aa4','Check meta keywords for MITRE technique reference','T1059.001'),mkClue('source-code','aa3','Inspect source for embedded malware config string','xor_key=0x4F;c2=update.modernservice[.]xyz'),mkClue('data-attribute','aa5','Look for data-threat-group attribute','APT-2841-PHANTOM')]},
  { name: 'Supply Chain Compromise', desc: 'Supply Chain Attack Investigation', category: 'forensics', nodes: [
    mkNode('sc1','step','Vendor Compromise Detection','Identify anomalous behavior in vendor-supplied software updates. Validate digital signatures and compare build hashes. Proceed to [[Build System Analysis]].',0,0),
    mkNode('sc2','tool','Build System Analysis','Examine CI/CD pipeline logs for unauthorized modifications. Check source repository integrity and commit signing. Proceed to [[Payload Extraction]].',300,0),
    mkNode('sc3','step','Payload Extraction','Isolate and reverse-engineer the trojanized component. Extract embedded payloads and identify injection points. Proceed to [[Blast Radius Assessment]].',600,0),
    mkNode('sc4','decision','Blast Radius Assessment','Determine which downstream customers and systems received the compromised update. Map deployment telemetry. Proceed to [[Remediation Plan]].',300,200),
    mkNode('sc5','output','Remediation Plan','Document containment actions, patch deployment strategy, and vendor notification procedures.',600,200),
  ], links: [mkLink('sc1','sc2'),mkLink('sc2','sc3'),mkLink('sc3','sc4'),mkLink('sc4','sc5')],
    clues: [mkClue('http-header','sc1','Inspect X-Build-Hash response header for tampered artifact','sha256:e3b0c44298fc1c149afbf4c8996fb924'),mkClue('network-request','sc3','XHR callback reveals C2 staging domain','telemetry.legit-vendor[.]cloud/update-check'),mkClue('console-log','sc4','Console output shows DLL sideloading indicator','[WARN] unsigned DLL loaded: mscoree_helper.dll')]},
  { name: 'Incident Timeline', desc: 'APT Incident Reconstruction', category: 'forensics', nodes: [
    mkNode('it1','step','Initial Access Vector','Determine how the adversary gained entry — spear-phish, exploit, or supply chain. Analyze logs from the earliest compromise timestamp. Proceed to [[Lateral Movement]].',0,0),
    mkNode('it2','step','Lateral Movement','Trace lateral movement via RDP, WMI, PsExec, or SMB. Map compromised hosts and credential usage. Proceed to [[Persistence Mechanism]].',300,0),
    mkNode('it3','tool','Persistence Mechanism','Identify persistence techniques: scheduled tasks, registry run keys, WMI subscriptions, or bootkit. Proceed to [[Data Staging]].',600,0),
    mkNode('it4','step','Data Staging','Locate staging directories where data was collected and compressed before exfiltration. Check for RAR/7z archives. Proceed to [[Exfiltration Analysis]].',0,200),
    mkNode('it5','tool','Exfiltration Analysis','Analyze network logs for data exfiltration channels — DNS tunneling, HTTPS to cloud storage, or covert C2. Proceed to [[Impact Assessment]].',300,200),
    mkNode('it6','output','Impact Assessment','Document full timeline, affected systems, data loss scope, and lessons learned for executive briefing.',600,200),
  ], links: [mkLink('it1','it2'),mkLink('it2','it3'),mkLink('it3','it4'),mkLink('it4','it5'),mkLink('it5','it6')],
    clues: [mkClue('base64','it4','Decode the base64 command used for staging','Y21kIC9jICJtYWtlY2FiIC9kIEM6XFN0YWdpbmcgL0YgZXhmaWwuZGRmIg=='),mkClue('hex-encoded','it5','Hex-encoded exfiltration domain in DNS query','65786669676174652e6576696c2e636f6d')]},
  { name: 'IOC Deep Dive', desc: 'Indicator of Compromise Analysis', category: 'defense', nodes: [
    mkNode('ioc1','step','IOC Triage','Ingest and prioritize incoming IOCs by type and confidence level. Deduplicate against existing threat intel. Proceed to [[Hash Analysis]].',0,0),
    mkNode('ioc2','tool','Hash Analysis','Submit file hashes to multi-engine scanners and sandbox detonation. Classify as malicious, suspicious, or benign. Proceed to [[Domain/IP Enrichment]].',300,0),
    mkNode('ioc3','tool','Domain/IP Enrichment','Enrich domains and IPs with WHOIS, passive DNS, geolocation, and reputation data. Identify infrastructure overlaps. Proceed to [[Behavioral Correlation]].',600,0),
    mkNode('ioc4','step','Behavioral Correlation','Correlate IOCs against endpoint telemetry and SIEM alerts to identify affected hosts and active compromise. Proceed to [[Detection Rule Creation]].',300,200),
    mkNode('ioc5','output','Detection Rule Creation','Author YARA, Sigma, and Snort rules based on confirmed IOCs. Deploy to detection pipeline and validate coverage.',600,200),
  ], links: [mkLink('ioc1','ioc2'),mkLink('ioc2','ioc3'),mkLink('ioc3','ioc4'),mkLink('ioc4','ioc5')],
    clues: [mkClue('source-code','ioc5','View source for embedded YARA rule snippet','rule APT_Backdoor { strings: $a = "beacon_config" condition: $a }'),mkClue('css-comment','ioc4','Hidden CSS comment contains sigma rule hint','/* sigma: process_creation | CommandLine contains "certutil -urlcache" */')]},
  { name: 'LOTL Detection', desc: 'Living-off-the-Land Technique Analysis', category: 'defense', nodes: [
    mkNode('ll1','step','Baseline Behavior','Establish normal baseline for system tool usage — PowerShell, certutil, mshta, rundll32. Profile legitimate admin patterns. Proceed to [[Anomaly Detection]].',0,0),
    mkNode('ll2','tool','Anomaly Detection','Apply statistical and ML-based anomaly detection to identify deviations from baseline. Flag unusual parent-child process relationships. Proceed to [[Process Tree Analysis]].',300,0),
    mkNode('ll3','step','Process Tree Analysis','Reconstruct process trees for flagged events. Identify suspicious execution chains like Explorer → cmd → powershell → net.exe. Proceed to [[Command Line Forensics]].',600,0),
    mkNode('ll4','tool','Command Line Forensics','Decode obfuscated command lines. Analyze encoded PowerShell, environment variable abuse, and argument smuggling. Proceed to [[LOTL Report]].',300,200),
    mkNode('ll5','output','LOTL Report','Document identified LOTL techniques, affected systems, and recommended detection improvements for SOC playbook.',600,200),
  ], links: [mkLink('ll1','ll2'),mkLink('ll2','ll3'),mkLink('ll3','ll4'),mkLink('ll4','ll5')],
    clues: [mkClue('console-log','ll4','Console reveals encoded PowerShell command','powershell -enc SQBFAFgAIAAoACgAbgBlAHcALQBvAGIAagBlAGMAdAApAC4AZABvAHcAbgBsAG8AYQBkAHMAdAByAGkAbgBnACgA'),mkClue('data-attribute','ll3','data-lolbin attribute reveals abused binary','data-lolbin="mshta.exe"')]},
  { name: 'C2 Infrastructure Mapping', desc: 'Command & Control Network Analysis', category: 'exploit', nodes: [
    mkNode('c2m1','step','DNS Anomaly Detection','Analyze DNS query logs for anomalous patterns — high entropy domains, unusual TLD usage, and excessive NXDOMAIN responses. Proceed to [[Fast-Flux Analysis]].',0,0),
    mkNode('c2m2','tool','Fast-Flux Analysis','Identify fast-flux networks by tracking rapid A-record changes and short TTL values. Map associated IP ranges. Proceed to [[Domain Generation Algorithm]].',300,0),
    mkNode('c2m3','step','Domain Generation Algorithm','Reverse-engineer DGA seed and algorithm from malware samples. Predict future domains for proactive blocking. Proceed to [[C2 Protocol Analysis]].',600,0),
    mkNode('c2m4','tool','C2 Protocol Analysis','Decode C2 protocol — beacon intervals, jitter, data encoding, and command structure. Identify framework fingerprints (Cobalt Strike, Sliver, Mythic). Proceed to [[Infrastructure Takedown Brief]].',300,200),
    mkNode('c2m5','output','Infrastructure Takedown Brief','Compile evidence package for registrar/hosting abuse reports and law enforcement referral. Document full C2 infrastructure map.',600,200),
  ], links: [mkLink('c2m1','c2m2'),mkLink('c2m2','c2m3'),mkLink('c2m3','c2m4'),mkLink('c2m4','c2m5')],
    clues: [mkClue('network-request','c2m3','XHR reveals DGA domain pattern','aG9zdA==.xjk2mf9a.top'),mkClue('http-header','c2m4','Response header contains beacon timing indicator','X-Beacon-Interval: 60s;jitter=0.37'),mkClue('meta-tag','c2m5','Meta tag contains JA3 hash for C2 fingerprinting','ja3:e7d705a3286e19ea42f587b344ee6865')]},
  ...CIVIC_ARC_TEMPLATES,
];
